// Code generated by Kitex v0.6.2. DO NOT EDIT.

package commentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	comment "minitok/kitex_gen/comment"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Action(ctx context.Context, Req *comment.ActionRequest, callOptions ...callopt.Option) (r *comment.ActionResponse, err error)
	List(ctx context.Context, Req *comment.ListRequest, callOptions ...callopt.Option) (r *comment.ListResponse, err error)
	Count(ctx context.Context, Req *comment.CountRequest, callOptions ...callopt.Option) (r *comment.CountResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCommentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCommentServiceClient struct {
	*kClient
}

func (p *kCommentServiceClient) Action(ctx context.Context, Req *comment.ActionRequest, callOptions ...callopt.Option) (r *comment.ActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Action(ctx, Req)
}

func (p *kCommentServiceClient) List(ctx context.Context, Req *comment.ListRequest, callOptions ...callopt.Option) (r *comment.ListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.List(ctx, Req)
}

func (p *kCommentServiceClient) Count(ctx context.Context, Req *comment.CountRequest, callOptions ...callopt.Option) (r *comment.CountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Count(ctx, Req)
}
